.PHONY: clean All

All:
	@echo "----------Building project:[ app0_ck802 - BuildSet ]----------"
	@make -r -f app0_ck802.mk -j 8 -C  ./ 
clean:
	@echo "----------Cleaning project:[ app0_ck802 - BuildSet ]----------"
